spring:
  application:
    name: product-service
  mongodb:
    uri: mongodb://root:password@localhost:27017/product-db?authSource=admin
  threads:
    virtual:
      enabled: true
server:
  port: 8080